import pytest
import os
import io
import json
import toml
import base64
from pathlib import Path
from unittest.mock import patch, MagicMock
from main import main
from logger import disable_logging, enable_logging

def run_wugong_no_password(args, config_path):
    """Run wugong command without providing -p flag."""
    full_args = ["main.py"] + args + ["--non-interactive", "--json"]
    
    disable_logging()
    # We mock get_imap_connection and send_email globally to avoid network issues
    with patch("sys.argv", full_args), \
         patch.dict(os.environ, {"WUGONG_CONFIG": str(config_path)}), \
         patch("mail.connector.MailConnector.get_imap_connection", return_value=MagicMock()), \
         patch("mail.sender.MailSender.send_email", return_value=True), \
         patch("sys.stdout", new=io.StringIO()) as mock_stdout, \
         patch("sys.stderr", new=io.StringIO()) as mock_stderr:
        try:
            main()
        except SystemExit as e:
            # We expect failure in some cases, so we don't raise here
            pass
        raw_output = mock_stdout.getvalue()
    enable_logging()
    return raw_output

def run_wugong_init(args, config_path):
    """Run wugong init command."""
    full_args = ["main.py", "init"] + args + ["--non-interactive", "--json"]
    
    disable_logging()
    with patch("sys.argv", full_args), \
         patch.dict(os.environ, {"WUGONG_CONFIG": str(config_path)}), \
         patch("sys.stdout", new=io.StringIO()) as mock_stdout, \
         patch("sys.stderr", new=io.StringIO()) as mock_stderr:
        try:
            main()
        except SystemExit:
            pass
        raw_output = mock_stdout.getvalue()
    enable_logging()
    return raw_output

@pytest.fixture
def temp_config(tmp_path):
    """Create a temporary config file with specified encryption settings."""
    def _create_config(encryption_enabled=False, encrypt_emails=False):
        config_path = tmp_path / "config.toml"
        config_data = {
            "general": {
                "encryption_enabled": encryption_enabled,
                "encrypt_emails": encrypt_emails,
                "default_account": "test"
            },
            "accounts": [
                {
                    "friendly_name": "test",
                    "email": "test@example.com",
                    "imap_server": "imap.example.com",
                    "imap_port": 993,
                    "smtp_server": "smtp.example.com",
                    "smtp_port": 465,
                    "username": "test@example.com",
                    "password": "encrypted_or_not"
                }
            ]
        }
        # If encryption is enabled, we need a salt and a canary for verification
        if encryption_enabled or encrypt_emails:
            # Simple dummy salt and canary for "password"
            # In a real scenario, this would be generated by wugong init
            from crypto_utils import encrypt_data
            salt_raw = b"wugong-test-salt"
            config_data["general"]["salt"] = base64.b64encode(salt_raw).decode()
            config_data["general"]["canary"] = encrypt_data("wugong", "password", salt_raw)
            
        with open(config_path, "w") as f:
            toml.dump(config_data, f)
        return config_path
    return _create_config

def test_list_local_no_encryption(temp_config):
    """Scenario 1: No encryption enabled. list --local should not require password."""
    config_path = temp_config(encryption_enabled=False, encrypt_emails=False)
    output = run_wugong_no_password(["list", "--local"], config_path)
    
    # Should return an empty list (no emails) instead of error
    try:
        res = json.loads(output)
        assert isinstance(res, list)
    except json.JSONDecodeError:
        pytest.fail(f"Failed to decode JSON output: {output}")

def test_init_with_encrypt_creds_no_password(tmp_path):
    """Test init --encrypt-creds without password fails in non-interactive mode."""
    config_path = tmp_path / "config.toml"
    output = run_wugong_init(["--encrypt-creds"], config_path)
    
    try:
        res = json.loads(output)
        assert res.get("status") == "error"
        assert "Encryption password must be provided" in res.get("message", "")
    except json.JSONDecodeError:
        pytest.fail(f"Failed to decode JSON output: {output}")

def test_init_with_encrypt_emails_no_password(tmp_path):
    """Test init --encrypt-emails without password fails in non-interactive mode."""
    config_path = tmp_path / "config.toml"
    output = run_wugong_init(["--encrypt-emails"], config_path)
    
    try:
        res = json.loads(output)
        assert res.get("status") == "error"
        assert "Encryption password must be provided" in res.get("message", "")
    except json.JSONDecodeError:
        pytest.fail(f"Failed to decode JSON output: {output}")

def test_init_no_encryption_no_password(tmp_path):
    """Test init with no encryption flags and no password succeeds."""
    config_path = tmp_path / "config.toml"
    output = run_wugong_init(["--no-encrypt-creds", "--no-encrypt-emails"], config_path)
    
    try:
        res = json.loads(output)
        assert res.get("status") == "success"
        
        # Verify config file
        with open(config_path, "r") as f:
            cfg = toml.load(f)
            assert cfg["general"]["encryption_enabled"] is False
            assert cfg["general"]["encrypt_emails"] is False
            assert cfg["general"]["salt"] == ""
    except json.JSONDecodeError:
        pytest.fail(f"Failed to decode JSON output: {output}")

def test_init_with_password_succeeds(tmp_path):
    """Test init with password and encryption flags succeeds."""
    config_path = tmp_path / "config.toml"
    password = "testpassword"
    output = run_wugong_init(["--encrypt-creds", "--encrypt-emails", "-p", password], config_path)
    
    try:
        res = json.loads(output)
        assert res.get("status") == "success"
        
        # Verify config file
        with open(config_path, "r") as f:
            cfg = toml.load(f)
            assert cfg["general"]["encryption_enabled"] is True
            assert cfg["general"]["encrypt_emails"] is True
            assert cfg["general"]["salt"] != ""
            assert "canary" in cfg["general"]
    except json.JSONDecodeError:
        pytest.fail(f"Failed to decode JSON output: {output}")

def test_list_local_with_email_encryption(temp_config):
    """Scenario 2: Email encryption enabled. list --local should require password."""
    config_path = temp_config(encryption_enabled=False, encrypt_emails=True)
    output = run_wugong_no_password(["list", "--local"], config_path)
    
    # Should return error message about password
    try:
        res = json.loads(output)
        assert res.get("status") == "error"
        assert "Encryption password is REQUIRED" in res.get("message", "")
    except json.JSONDecodeError:
        pytest.fail(f"Failed to decode JSON output: {output}")

def test_account_list_verbose_no_encryption(temp_config):
    """Scenario 3: No encryption enabled. account list --verbose should not require password."""
    config_path = temp_config(encryption_enabled=False, encrypt_emails=False)
    output = run_wugong_no_password(["account", "list", "--verbose"], config_path)
    
    try:
        res = json.loads(output)
        assert isinstance(res, list)
        assert res[0]["friendly_name"] == "test"
    except json.JSONDecodeError:
        pytest.fail(f"Failed to decode JSON output: {output}")

def test_account_list_verbose_with_encryption(temp_config):
    """Scenario 4: Encryption enabled. account list --verbose should skip server stats if no password."""
    config_path = temp_config(encryption_enabled=True, encrypt_emails=False)
    output = run_wugong_no_password(["account", "list", "--verbose"], config_path)
    
    try:
        res = json.loads(output)
        # Should still return account list but server stats will be N/A
        assert isinstance(res, list)
        assert res[0]["friendly_name"] == "test"
        assert res[0]["server_total"] == "N/A"
    except json.JSONDecodeError:
        pytest.fail(f"Failed to decode JSON output: {output}")

def test_send_no_encryption(temp_config):
    """Scenario 5: No encryption enabled. send should not require password."""
    config_path = temp_config(encryption_enabled=False, encrypt_emails=False)
    output = run_wugong_no_password(["send", "--to", "a@b.com", "--subject", "hi", "--body", "test"], config_path)
    # Should not be a password error
    try:
        res = json.loads(output)
        assert "Encryption password is REQUIRED" not in str(res)
    except json.JSONDecodeError:
        # In this case it might fail due to other things but not password
        assert "Encryption password is REQUIRED" not in output

def test_send_with_encryption_requires_password(temp_config):
    """Scenario 6: Encryption enabled. send should require password to decrypt SMTP credentials."""
    config_path = temp_config(encryption_enabled=True, encrypt_emails=False)
    output = run_wugong_no_password(["send", "--to", "a@b.com", "--subject", "hi", "--body", "test"], config_path)
    
    try:
        res = json.loads(output)
        assert res.get("status") == "error"
        assert "Encryption password is REQUIRED" in res.get("message", "")
    except json.JSONDecodeError:
        pytest.fail(f"Failed to decode JSON output: {output}")
